name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
            npm install
            npm install electron-packager

      - name: Build and deploy
        run: |
          npm start &
          sleep 10  # Ajoutez un délai pour donner du temps à l'application pour démarrer (ajustez si nécessaire)
          echo "Contents of deploy directory:"
          ls -R deploy/
          ps aux | grep node
          cat deploy/.nojekyll  # Assurez-vous que le fichier .nojekyll a été créé
          jobs
          wait  # Attend que toutes les tâches en arrière-plan se terminent

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          user_name: GitHub Actions
          user_email: actions@github.com
          publish_branch: gh-pages
